### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by stefanpenner** [felixrieseberg/electron-code-editor#1]
```
 s/f/electron-code-editor ╍ yarn; yarn start                         (1s 446ms)
yarn install v0.16.1
info No lockfile found.
warning electron-code-editor@1.0.0: "dependencies" has dependency "electron" with range "^1.4.7" that collides with a dependency in "devDependencies" of the same name with version "^1.4.1"
[1/4] 🔍  Resolving packages...
warning electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 52.66s.
yarn start v0.16.1
$ electron .
App threw an error during load
Error: Cannot find module 'electron-default-menu'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/spenner/src/felixrieseberg/electron-code-editor/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/spenner/src/felixrieseberg/electron-code-editor/menu.js:1:100)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Comment by stefanpenner** [comment]
\w npm

```
> electron-code-editor@1.0.0 start /Users/spenner/src/felixrieseberg/electron-code-editor
> electron .

App threw an error during load
Error: Cannot find module 'electron-default-menu'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/spenner/src/felixrieseberg/electron-code-editor/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/spenner/src/felixrieseberg/electron-code-editor/menu.js:1:100)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

```
{ 'electron-code-editor': '1.0.0',
  npm: '3.10.9',
  ares: '1.10.1-DEV',
  cldr: '30.0.2',
  http_parser: '2.7.0',
  icu: '58.1',
  modules: '51',
  node: '7.1.0',
  openssl: '1.0.2j',
  tz: '2016g',
  unicode: '9.0',
  uv: '1.10.0',
  v8: '5.4.500.36',
  zlib: '1.2.8' }
```
